### ISSUE TITLE
form.validationState.isRejected is false while there are errors? 

### ISSUE THREAD

**Issue by eelke** [CrowdStrike/ember-headless-form#120]
I have a form, with yup validation. Validation works fine, however I would expect `form.validationState.isRejected` to be true if there are errors in the form. 

When I keep the form empty, validate and output the validationState, I see this:

```JSON
{
  "isPending": false,
  "isResolved": true,
  "value": {
    "name": [
      {
        "type": "required",
        "value": "",
        "message": {
          "key": "field_required"
        }
      },
      {
        "type": "min",
        "value": "",
        "message": {
          "key": "field_too_short",
          "value": 5
        }
      }
    ],
    "email": [
      {
        "type": "required",
        "value": "",
        "message": {
          "key": "field_required"
        }
      }
    ],
    "akkoord": [
      {
        "type": "oneOf",
        "value": false,
        "message": {
          "key": "field_invalid_oneoff",
          "values": {
            "oneOf": true
          }
        }
      }
    ]
  },
  "isRejected": false
}    
``` 

Whenever there are no errors in the form, `form.validationState.value` is an empty object. 
I would expect `isRejected` to also be true in this case, or am I misunderstanding the idea here?

Some of the package versions in my package.json:
```JSON
  "ember-cli": "~4.7.0",
  "ember-headless-form": "^1.0.0-beta.1",
  "ember-headless-form-yup": "^1.0.0-beta.0",
  "yup": "^1.1.1"
```

**Comment by simonihmig** [comment]
I think this is a misunderstanding, probably we should document this better...

The meaning of `isRejected` is that the validation function threw an error, and did not return a validation result we can work with! 

Technical detail: this is coming from https://github.com/tracked-tools/ember-async-data, and in a TypeScript codebase it means you cannot even access `form.validationState.value` (gives a type error) when `form.validationState.isRejected` is true.

For the use case of rendering something within the form when the validation worked, but returned validation errors, you can use the yielded `form.isInvalid`!
