### ISSUE TITLE
When is 1.0?

### ISSUE THREAD

**Issue by NullVoxPopuli** [CrowdStrike/ember-headless-form#183]
atm, the latest version is just a beta: https://www.npmjs.com/package/ember-headless-form?activeTab=versions

**Comment by ynotdraw** [comment]
I think we could _probably_ cut a 1.0 now if we wanted to?  What do you think @simonihmig ?

**Comment by simonihmig** [comment]
Yeah, I was hoping to do so, but wondered if we need to consider support for server-originating validation errors (https://github.com/CrowdStrike/ember-headless-form/issues/143) before calling our APIs stable? But we can also consider it "just" a missing feature. I don't really anticipate that we would need to break any existing API when adding it later. What do you think?

**Comment by ynotdraw** [comment]
> I don't really anticipate that we would need to break any existing API when adding it later.

Yeah, this makes me feel as though fixing #143 could be a minor bump when ready, especially if no breaking API changes for that! 🎉

**Comment by bartocc** [comment]
Hey, just chiming in to know that status of this issue 😊

**Comment by ynotdraw** [comment]
I think it's probably ready for a non-beta 1.0! I know we haven't hit any issues with it after about 5-6 months of use. What do you think @simonihmig?

**Comment by simonihmig** [comment]
Yeah, we definitely need to do that! I was just embarrassed by myself the other day when I realized I haven't done this yet...

However, I came across some issue on Discord where passing an ember-data object to `@data` did not work. I want to look into this, as I think it _should_ work. But hope we can finalize this next week (this week was a bit crazy)!

**Comment by bartocc** [comment]
I am experimenting with `@data` as a changeset wrapping a POJO at the moment, and will then wrap an ember-data object in the changeset.

I'll let you know if I hit any issue

**Comment by simonihmig** [comment]
> When is 1.0

Now, finally! 😅

**Comment by NullVoxPopuli** [comment]
yay!!!
