### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by evoactivity** [CrowdStrike/ember-headless-form#292]
Creating an issue incase it hasn't been noticed.

**Comment by mcfiredrill** [comment]
![Screenshot 2024-03-21 at 9 00 24 AM](https://github.com/CrowdStrike/ember-headless-form/assets/66243/88de6018-4e62-475f-b9f6-a7b32d694664)
Here's what I'm seeing

**Comment by eelke** [comment]
Ping @simonihmig

**Comment by averydev** [comment]
Holler if I can help with this.

**Comment by acorncom** [comment]
@averydev if you have time to work on a PR, I'm sure all of us would appreciate it 😄

**Comment by simonihmig** [comment]
Sorry for the delay! I think I have found the root cause: https://github.com/CrowdStrike/ember-oss-docs/pull/23.

Hope to get this fixed asap here!
