### ISSUE TITLE
Rethink module exports

### ISSUE THREAD

**Issue by simonihmig** [CrowdStrike/ember-headless-form#39]
Should we do this as we do now:

```
import HeadlessForm from 'ember-headless-form/components/headless-form';
```

Or rather provide all public imports from index:

```
import { HeadlessForm } from 'ember-headless-form';
```

Or both?

**Comment by NullVoxPopuli** [comment]
```js
import { HeadlessForm } from 'ember-headless-form';
```

is my preference, because:
- this addon only only provides one root component, and has nothing to tree shake
- fewer path segments are easier to type
- root-level exports like this are a clear indicator of "public API"
- less noisy imports when folks use exclusively strict mode / gjs/gts
