### ISSUE TITLE
Auto-focus on first invalid input

### ISSUE THREAD

**Issue by jedateach** [CrowdStrike/ember-headless-form#528]
A great user experience / accessible form focuses on the first invalid input.

I've hacked together something that finds the first invalid field via the `handleInvalid` HeadlessForm action.

Is this kind of functionality common enough, or suitable for adding to Ember Headless Forms?
If not, could we make something easily pluggable?

**Comment by simonihmig** [comment]
Hm, not sure tbh. Like is programmatically changing focus really something that would help a11y, or rather be detrimental? I would want to be really sure about this, like having a subject matter export confirm this, before baking this in.

Curious, would something like `document.querySelector('input:invalid').focus()` work? (not tested)
If it's easy enough to implement this on the consumer side, then I'd suggest that.

**Comment by jedateach** [comment]
Now that I understand that `ember-headless-form` can be wrapped like the toucan design system does, I think that would be the right layer for this kind of behaviour. Closing.
